name: Update Messi Stats

on:
  schedule:
    # Jueves a las 10:00 hs ART (13:00 UTC)
    - cron: '0 13 * * 4'
    # Domingos a las 23:59 hs ART (02:59 UTC del Lunes)
    - cron: '59 2 * * 1'
  workflow_dispatch:
    # Permite la ejecución manual desde la pestaña Actions en GitHub

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Sync Statistics to Firebase
        run: npm run update-stats
        env:
          UPDATER_PASSWORD: ${{ secrets.UPDATER_PASSWORD }}
